Meaning of the fields of fitinfo in the fidmodel object, generated by elis
==========================================================================
cf         = cost function
cfth       = theoretical value of the cost function (chi^2/2)
cf95       = 95% point of the theoretical distribution of the cf
cf05       = 5% point of the theoretical distribution of the cf
F          = number of frequencies
freepar    = number of free parameters
iterations = performed iterations
dcf        = last change of the cost function
dprel      = last maximum of the relative changes of parameters
lambda     = last lambda value (for Levenberg-Marquardt, otherwise NaN)
mmerror    = approximate mean model error
meanabstf  = mean absolute value of the transfer function
AIC        = Akaike information criterion (AIC): cost*(1+np/F)
MDL        = Rissanen's information criterion
condnum    = condition number of the matrix actually decomposed
             or inverted in the last cycle
condnumJ   = condition number of J in the last cycle
fscale     = scaling frequency for internal calculations
termcause  = cause of termination:
             'itmax' for iteration number limit,
             'dcf' for small dcf
             'dp' for small dp
             'GUI' for GUI request
runtime    = total running time in seconds
errorweighting = type of the weighting used: 'linear', 'nonlinear', 'interpolated nonlinear'
                 default: 'linear'

More information can be obtained from a second output argument (for advanced users only)
----------------------------------------------------------------------------------------
Usage: [pdat,devitinfo]=elis((Fdat,domain,numord,denomord,runmod,devrunmod)
Fields of devitinfo:
cfv = vector of the cost function values in the iteration steps; for
      the LM algorithm, the second column contains the lambda values.
      length: iterations+1 (0:iterations)
J = the Jacobian of the last iteration step
w = linear weight vector of the cost function: C=1/2*(w.*E)'(w.*E) 

See also: elis runmod, elis devrunmod