function fddems1
%FDDEMS1  Return fdident demo information to the MATLAB Demo: general demos.

%       Copyright (c) I. Kollar and Vrije Universiteit Brussel, ELEC, 1991-98
%       All rights reserved.
%       $Revision: $
%       Last modified: 05-Apr-1997, I. Kollar

c=computer;
if strcmp(c(1:2),'PC')
  textpause='p'; %Allow switch to Command Window by pressing button
end

labelList = str2mat( ...
    'Simulation example',...
    'Self-study problems',...
    'Time domain identification',...
    'Excitation signal design',...
    'Crest factor minimization',...
    'Preparation of time function',...
    'Max. length binary sequence',...
    'Discrete interval binary seq.',...
    'Complex ratio geometric mean',...
    'Closest 2-D point pairs',...
    'Synchronization and averaging');

nameList = str2mat( ...
   'simudemo',...
   'fdcourse',...
   'eltpexpl',...
   'optexdem',...
   'mscldemo',...
   'msprdemo',...
   'mlbsdemo',...
   'dibsdemo',...
   'gmeandem',...
   'pairsdem',...
   'varandem');

figureFlagList = [ones(1,11)];

cmdlnwin(labelList,nameList,figureFlagList);
%
%End of fddems1
