function fddems2
%FDDEMS2   Return fdident demo information to the MATLAB Demo: book demos.

%       Copyright (c) I. Kollar and Vrije Universiteit Brussel, ELEC, 1991-98
%       All rights reserved.
%       $Revision: $
%       Last modified: 05-Apr-1997, I. Kollar

c=computer;
if strcmp(c(1:2),'PC')
  textpause='p'; %Allow switch to Command Window by pressing button
end

labelList = str2mat( ...
    'Identify: flexible robot arm',...
    'Identify: passive octave filter',...
    'Identify: active lowpass filter',...
    'Input channel compensation',...
    'Identify: electrical machine',...
    'Identify: crankcase',...
    'Identify: aluminum plates',...
    'Identify: rectangular plate',...
    'Transfer function estimation',...
    'Cable fault location');

nameList = str2mat( ...
    'rarmdemo',...
    'bandpdem',...
    'lowpdemo',...
    'inpchdem',...
    'emachdem',...
    'crankdem',...
    'alupldem',...
    'glfibdem',...
    'lpelabex',...
    'cabledem');

figureFlagList = [ones(1,10)];

cmdlnwin(labelList,nameList,figureFlagList);
%
%End of fddems2

